Traceback (most recent call last):
  File "/home/karol/Desktop/BoringwithPythob/errorExample.py", line 9, in <module>
    spam()
  File "/home/karol/Desktop/BoringwithPythob/errorExample.py", line 4, in spam
    bacon()
  File "/home/karol/Desktop/BoringwithPythob/errorExample.py", line 7, in bacon
    raise Exception('This is the error message')
Exception: This is the error message
